name: Build and Push Docker Image

on:
  workflow_run:
    workflows:
      - Test Application
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: output code
      uses: actions/checkout@v3

    - name: login DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: create and send Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: zhangbolun2/dockerized-js-app:latest